export const sovrynSwapNetworkAddress = '{{SovrynSwapNetwork.address}}'
export const WRBTCAddress = '{{WRBTCToken.address}}'
export const USDTAddress = '{{USDTToken.address}}'
export const vestingRegistry1 = '{{VestingRegistry1.address}}'
export const vestingRegistry2 = '{{VestingRegistry2.address}}'
export const vestingRegistry3 = '{{VestingRegistry3.address}}'
